Implementaçao feita do UC-Avaliar cliente. Resolve #90.
marcosdosea/MaisServicos pull request #119
Opened 2023-09-18 02:51 UTC by TSjadness

Implementação do  core, service e controller de UC- Avaliar cliente

2023-09-18 22:43 UTC, vitorolive99 requested changes
Refatorar o código de acordo com os comentários.

2023-09-18 22:43 UTC, vitorolive99 commented on Codigo/MaisServicos/Core/Service/IAvaliarClienteService.cs
> +    public interface IAvaliarClienteService
O caso de uso manter avaliação cliente é um crud de avaliações, então os métodos recebem ou retornam um tipo Avaliacao como parâmetro, não um tipo Pessoa.

2023-09-18 22:43 UTC, vitorolive99 commented on Codigo/MaisServicos/MaisServicosWeb/Controllers/AvaliarClienteController.cs
> +                var client = _mapper.Map<Pessoa>(avaliarClienteViewModel);
Alterar tipo no mapper para Avaliacao.

2023-09-18 22:43 UTC, vitorolive99 commented on Codigo/MaisServicos/MaisServicosWeb/Mappers/AvaliarClienteProfile.cs
> +            CreateMap<AvaliarClienteViewModel, Pessoa>().ReverseMap();
Alterar tipo de Passoa para Avaliacao.

2023-09-18 22:43 UTC, vitorolive99 commented on Codigo/MaisServicos/MaisServicosWeb/Controllers/AvaliarClienteController.cs
Alterar o tipo de Pessoa para Avaliacao em todas as ocorrências.

2023-09-18 22:43 UTC, vitorolive99 commented on Codigo/MaisServicos/Service/AvaliarClienteService.cs
Alterar o tipo de Pessoa para Avaliacao em todas as ocorrências.

2023-09-19 03:49 UTC, TSjadness commented
Correção feita.
Por favor revisar novamente.

2023-09-20 01:21 UTC, vitorolive99 approved these changes

2023-09-20 01:21 UTC, merged